// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/debug": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/certifications": {
    params: {};
  };
  "/certification_master": {
    params: {};
  };
  "/health_master": {
    params: {};
  };
  "/solar_master": {
    params: {};
  };
  "/nil_master": {
    params: {};
  };
  "/discover": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/disclaimer": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/debug" | "/services" | "/about" | "/certifications" | "/certification_master" | "/health_master" | "/solar_master" | "/nil_master" | "/discover" | "/contact" | "/privacy" | "/terms" | "/disclaimer";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/debug.tsx": {
    id: "routes/debug";
    page: "/debug";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/certifications.tsx": {
    id: "routes/certifications";
    page: "/certifications";
  };
  "routes/certification_master.tsx": {
    id: "routes/certification_master";
    page: "/certification_master";
  };
  "routes/health_master.tsx": {
    id: "routes/health_master";
    page: "/health_master";
  };
  "components/solarMaster/SolarMaster.tsx": {
    id: "components/solarMaster/SolarMaster";
    page: "/solar_master";
  };
  "components/nilMaster/NILMaster.tsx": {
    id: "components/nilMaster/NILMaster";
    page: "/nil_master";
  };
  "routes/discover.tsx": {
    id: "routes/discover";
    page: "/discover";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/disclaimer.tsx": {
    id: "routes/disclaimer";
    page: "/disclaimer";
  };
};